### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by it-can-bee** [jeffchen006/OpenTracer#4]
看cache的文件夹是否存在OpenTracer/cache/，没有的话新建一个空白的cache文件夹，运行python3 main.py即可

**Comment by jeffchen006** [comment]
Thank you for reporting the issue!

It has been fixed at a new [commit](https://github.com/jeffchen006/OpenTracer/commit/e0881d734c65fabaeaf63a05093b92db31ff140f)
